// Package assets provides access to embedded nuclei templates and rules.
// Files are loaded from assets_gen.go (generated by scripts/gen_assets.sh).
// When assets_gen.go is not present (open-source builds), all functions
// return empty results gracefully.
package assets

import (
	"fmt"
	"io/fs"
	"path"
	"strings"
	"time"
)

// file holds a single embedded asset (populated by generated init()).
type file struct {
	Path string
	Data []byte
}

var files []file

// RegisterFile is called by generated code to add an embedded file.
func RegisterFile(p string, data []byte) {
	files = append(files, file{Path: p, Data: data})
}

// List returns all embedded file paths.
func List() []string {
	out := make([]string, len(files))
	for i, f := range files {
		out[i] = f.Path
	}
	return out
}

// ReadFile returns the content of an embedded file.
func ReadFile(name string) ([]byte, error) {
	for _, f := range files {
		if f.Path == name {
			return f.Data, nil
		}
	}
	return nil, fmt.Errorf("asset %q not found", name)
}

// ListDir returns all files under a directory prefix.
func ListDir(dir string) []string {
	prefix := dir
	if !strings.HasSuffix(prefix, "/") {
		prefix += "/"
	}
	var out []string
	for _, f := range files {
		if strings.HasPrefix(f.Path, prefix) || f.Path == dir {
			out = append(out, f.Path)
		}
	}
	return out
}

// FS returns an fs.FS rooted at the given directory.
func FS(root string) fs.FS { return &memFS{root: root} }

type memFS struct{ root string }

func (m *memFS) Open(name string) (fs.File, error) {
	full := path.Join(m.root, name)
	data, err := ReadFile(full)
	if err != nil {
		return nil, fmt.Errorf("asset %q not found", name)
	}
	return &memFile{name: path.Base(name), data: data}, nil
}

type memFile struct {
	name string
	data []byte
	off  int
}

func (f *memFile) Stat() (fs.FileInfo, error) { return f, nil }
func (f *memFile) Read(b []byte) (int, error) {
	if f.off >= len(f.data) {
		return 0, fmt.Errorf("EOF")
	}
	n := copy(b, f.data[f.off:])
	f.off += n
	return n, nil
}
func (f *memFile) Close() error               { return nil }
func (f *memFile) Name() string               { return f.name }
func (f *memFile) Size() int64                 { return int64(len(f.data)) }
func (f *memFile) Mode() fs.FileMode          { return 0444 }
func (f *memFile) ModTime() time.Time         { return time.Time{} }
func (f *memFile) IsDir() bool                { return false }
func (f *memFile) Sys() any                   { return nil }
