//go:build ignore

// gen_payloads.go reads payloads.yaml and generates pkg/payload/registry_gen.go
// with all payloads XOR-obfuscated. Run: go run scripts/gen_payloads.go
package main

import (
	"bufio"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	root := findRoot()
	yamlPath := filepath.Join(root, "payloads.yaml")
	outPath := filepath.Join(root, "pkg", "payload", "registry_gen.go")

	// Parse YAML (minimal parser — no external deps)
	categories, err := parsePayloadsYAML(yamlPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse %s: %v\n", yamlPath, err)
		os.Exit(1)
	}

	// Generate XOR key (32 bytes)
	key := make([]byte, 32)
	if _, err := rand.Read(key); err != nil {
		fmt.Fprintf(os.Stderr, "rand: %v\n", err)
		os.Exit(1)
	}

	// Generate Go source
	var b strings.Builder
	b.WriteString("// Code generated by scripts/gen_payloads.go; DO NOT EDIT.\n")
	b.WriteString("package payload\n\nfunc init() {\n")
	b.WriteString(fmt.Sprintf("\tSetKey([]byte{%s})\n\n", formatBytes(key)))

	catNames := sortedKeys(categories)
	for _, cat := range catNames {
		items := categories[cat]
		var keys []string
		for _, item := range items {
			fullKey := cat + "." + item.name
			enc := xorEncode([]byte(item.value), key)
			hexStr := hex.EncodeToString(enc)
			b.WriteString(fmt.Sprintf("\tRegister(%q, %q)\n", fullKey, hexStr))
			keys = append(keys, fullKey)
		}
		b.WriteString(fmt.Sprintf("\tRegisterList(%q, []string{", cat))
		for i, k := range keys {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(fmt.Sprintf("%q", k))
		}
		b.WriteString("})\n\n")
	}

	b.WriteString("}\n")

	if err := os.WriteFile(outPath, []byte(b.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", outPath, err)
		os.Exit(1)
	}

	total := 0
	for _, items := range categories {
		total += len(items)
	}
	fmt.Printf("[+] Generated %s: %d categories, %d payloads\n", outPath, len(categories), total)
}

type payloadItem struct {
	name  string
	value string
}

// parsePayloadsYAML is a minimal YAML parser for our specific format:
//
//	category_name:
//	  - name: value
//	  - name: |
//	      multiline value
func parsePayloadsYAML(path string) (map[string][]payloadItem, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	categories := make(map[string][]payloadItem)
	var currentCat string
	var currentItem *payloadItem
	var multiline bool
	var mlIndent int
	var mlLines []string

	flushMultiline := func() {
		if currentItem != nil && multiline {
			currentItem.value = strings.Join(mlLines, "\n")
			categories[currentCat] = append(categories[currentCat], *currentItem)
			currentItem = nil
			multiline = false
			mlLines = nil
		}
	}

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()

		// Skip comments and empty lines at top level
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			if multiline && trimmed == "" {
				mlLines = append(mlLines, "")
			}
			continue
		}

		// Detect indent level
		indent := len(line) - len(strings.TrimLeft(line, " \t"))

		// If in multiline mode, check if still indented
		if multiline {
			if indent >= mlIndent {
				mlLines = append(mlLines, line[mlIndent:])
				continue
			}
			flushMultiline()
		}

		// Category line: "category_name:"
		if !strings.HasPrefix(line, " ") && !strings.HasPrefix(line, "\t") && strings.HasSuffix(trimmed, ":") && !strings.Contains(trimmed, " - ") {
			flushMultiline()
			currentCat = strings.TrimSuffix(trimmed, ":")
			continue
		}

		// Item line: "  - name: value" or "  - name: |"
		if strings.HasPrefix(trimmed, "- ") && currentCat != "" {
			flushMultiline()
			rest := strings.TrimPrefix(trimmed, "- ")
			colonIdx := strings.Index(rest, ": ")
			if colonIdx < 0 {
				// "- name:" with no value means empty or next line is multiline
				name := strings.TrimSuffix(rest, ":")
				currentItem = &payloadItem{name: name}
				continue
			}
			name := rest[:colonIdx]
			val := rest[colonIdx+2:]

			if val == "|" || val == "|-" {
				// Multiline block
				currentItem = &payloadItem{name: name}
				multiline = true
				mlIndent = indent + 4 // expect 4 more spaces
				if mlIndent < indent+2 {
					mlIndent = indent + 2
				}
				mlLines = nil
				continue
			}

			// Single-line value — strip quotes
			val = stripQuotes(val)
			categories[currentCat] = append(categories[currentCat], payloadItem{name: name, value: val})
			continue
		}
	}
	flushMultiline()

	return categories, scanner.Err()
}

func stripQuotes(s string) string {
	if len(s) >= 2 {
		if (s[0] == '"' && s[len(s)-1] == '"') || (s[0] == '\'' && s[len(s)-1] == '\'') {
			return s[1 : len(s)-1]
		}
	}
	return s
}

func xorEncode(data, key []byte) []byte {
	out := make([]byte, len(data))
	for i, b := range data {
		out[i] = b ^ key[i%len(key)]
	}
	return out
}

func formatBytes(b []byte) string {
	parts := make([]string, len(b))
	for i, v := range b {
		parts[i] = fmt.Sprintf("0x%02x", v)
	}
	return strings.Join(parts, ", ")
}

func sortedKeys(m map[string][]payloadItem) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func findRoot() string {
	// Walk up from executable/cwd to find go.mod
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			fmt.Fprintln(os.Stderr, "cannot find project root (go.mod)")
			os.Exit(1)
		}
		dir = parent
	}
}
