#!/usr/bin/env bash
# scripts/gen_assets.sh — encrypt nuclei-templates/ and rules/ into Go source.
# Run from project root: bash scripts/gen_assets.sh
#
# Generates:
#   internal/assets/assets_gen.go  — encrypted data + decryption (do NOT commit)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ASSETS_DIR="$ROOT/internal/assets"
OUT="$ASSETS_DIR/assets_gen.go"

mkdir -p "$ASSETS_DIR"

# ---------------------------------------------------------------------------
# 1. Generate AES-256-CBC key + IV
# ---------------------------------------------------------------------------
KEY_HEX=$(openssl rand -hex 32)
IV_HEX=$(openssl rand -hex 16)
echo "[*] Generated AES-256-CBC key"

# ---------------------------------------------------------------------------
# 2. Encrypt helper
# ---------------------------------------------------------------------------
encrypt_b64() {
    openssl enc -aes-256-cbc -nosalt -K "$KEY_HEX" -iv "$IV_HEX" | base64 -w0
}

# ---------------------------------------------------------------------------
# 3. Write Go header
# ---------------------------------------------------------------------------
cat > "$OUT" << GOHEADER
// Code generated by scripts/gen_assets.sh; DO NOT EDIT.
package assets

import (
	"crypto/aes"
	"crypto/cipher"
	"encoding/base64"
	"encoding/hex"
)

var encKey = "${KEY_HEX}"
var encIV = "${IV_HEX}"

type encFile struct {
	EncPath string
	EncData string
}

var encryptedFiles = []encFile{
GOHEADER

# ---------------------------------------------------------------------------
# 4. Encrypt each file
# ---------------------------------------------------------------------------
encode_dir() {
    local dir="$1"
    [[ -d "$ROOT/$dir" ]] || return 0
    local olddir
    olddir=$(pwd)
    cd "$ROOT"
    find "$dir" -type f | sort | while IFS= read -r relpath; do
        [[ -z "$relpath" ]] && continue
        enc_path=$(printf '%s' "$relpath" | encrypt_b64)
        enc_data=$(encrypt_b64 < "$relpath")
        printf '\t{EncPath: "%s", EncData: "%s"},\n' "$enc_path" "$enc_data" >> "$OUT"
    done
    cd "$olddir"
}

encode_dir "nuclei-templates"
encode_dir "rules"

# ---------------------------------------------------------------------------
# 5. Write Go footer — decryption + init
# ---------------------------------------------------------------------------
cat >> "$OUT" << 'GOFOOTER'
}

func decryptAES(hexKey, hexIV, b64data string) ([]byte, error) {
	key, err := hex.DecodeString(hexKey)
	if err != nil {
		return nil, err
	}
	iv, err := hex.DecodeString(hexIV)
	if err != nil {
		return nil, err
	}
	ciphertext, err := base64.StdEncoding.DecodeString(b64data)
	if err != nil {
		return nil, err
	}
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, err
	}
	mode := cipher.NewCBCDecrypter(block, iv)
	mode.CryptBlocks(ciphertext, ciphertext)
	// PKCS7 unpad
	if len(ciphertext) == 0 {
		return ciphertext, nil
	}
	pad := int(ciphertext[len(ciphertext)-1])
	if pad > aes.BlockSize || pad == 0 {
		return ciphertext, nil
	}
	return ciphertext[:len(ciphertext)-pad], nil
}

func init() {
	for _, ef := range encryptedFiles {
		pathBytes, err := decryptAES(encKey, encIV, ef.EncPath)
		if err != nil {
			continue
		}
		dataBytes, err := decryptAES(encKey, encIV, ef.EncData)
		if err != nil {
			continue
		}
		RegisterFile(string(pathBytes), dataBytes)
	}
}
GOFOOTER

TOTAL=$(grep -c 'EncPath:' "$OUT" || true)
echo "[+] Generated $OUT: $TOTAL files encrypted"
